### ISSUE TITLE
API Explanation

### ISSUE THREAD

**Issue by 360views** [JoshuaR503/Stock-Market-App#2]
Please expalin how to get and change API keys (where do you change them exactly) - it's not clear

**Comment by JoshuaR503** [comment]
If you go to `lib/keys/api_keys.dart`, you will see the instructions.

**Comment by 360views** [comment]
The instructions in the file are not clear - 

I have registered all the APIs and replaced in the api_keys.dart file, for example:

**const String kAlphaVantageKey = '0F3ACJ1PZI532JGI';**

I do not understand what do you mean by "// TODO: Remove the 'package:sma/key.dart' package and replace the varibales' value with your own API keys."

Should I delete "import 'package:sma/key.dart';" from the api_keys.dart file? Should I create a new file key.dart?

Can you please explain in details? Thanks

**Comment by JoshuaR503** [comment]
@360views, you should not create a new file called `key.dart`. You just have to remove the import `import 'package:sma/key.dart;`. Please let me know if you need clarification.

**Comment by 360views** [comment]
Ok - Thnaks!

Please check your app I think something is wrong as it does't load the
stocks (try the Android app)

Regarding the lib/keys/api_keys.dart :

So I should keep all the const... (I deleted the import)

For example:

const String kSentryDomainNameSystem = 'https://
a65da574b7ad418659e0338a85e32b8f@o394457.ingest.sentry.io/5244586';
const String kAlphaVantageKey = '0F3VBJ1PZI546JGI';
const String kFinnhubKey = 'br174V6rh5reisn50e50';
const String kNewsKey = '06072e7d9717471896993fc8030fe1c5';
SHOULD I USE WITH "" OR WITH '' ?? PLEASE SHOW ME AN EXAMPLE


--------------

*When I run with ''.... I get these errors in the DEBUG CONSOLE:*


Launching lib\main.dart on Android SDK built for x86 64 in debug mode...

Compiler message:
/C:/flutter/.pub-cache/hosted/
pub.dartlang.org/dio-2.2.2/lib/src/dio_http_headers.dart:55:8: Error: The
method 'DioHttpHeaders.add' has fewer named arguments than those of
overridden method 'HttpHeaders.add'.
  void add(String name, value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:694:8:
Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^
/C:/flutter/.pub-cache/hosted/
pub.dartlang.org/dio-2.2.2/lib/src/dio_http_headers.dart:70:8: Error: The
method 'DioHttpHeaders.set' has fewer named arguments than those of
overridden method 'HttpHeaders.set'.
  void set(String name, Object value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:703:8:
Context: This is the overridden method ('set').
  void set(String name, Object value,
       ^

Compiler message:
/C:/flutter/.pub-cache/hosted/
pub.dartlang.org/dio-2.2.2/lib/src/dio_http_headers.dart:55:8: Error: The
method 'DioHttpHeaders.add' has fewer named arguments than those of
overridden method 'HttpHeaders.add'.
  void add(String name, value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:694:8:
Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^
/C:/flutter/.pub-cache/hosted/
pub.dartlang.org/dio-2.2.2/lib/src/dio_http_headers.dart:70:8: Error: The
method 'DioHttpHeaders.set' has fewer named arguments than those of
overridden method 'HttpHeaders.set'.
  void set(String name, Object value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:703:8:
Context: This is the overridden method ('set').
  void set(String name, Object value,
       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation:
null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero
exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 15s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by JoshuaR503** [comment]
@360views, I pushed a new commit yesterday. Have you pulled the new changes?

**Comment by 360views** [comment]
Hi - I did a new clone and changed the APIs - I still get the same errors:

Launching lib\main.dart on Android SDK built for x86 64 in debug mode...

Compiler message:
/C:/flutter/.pub-cache/hosted/
pub.dartlang.org/dio-2.2.2/lib/src/dio_http_headers.dart:55:8: Error: The
method 'DioHttpHeaders.add' has fewer named arguments than those of
overridden method 'HttpHeaders.add'.
  void add(String name, value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:694:8:
Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^
/C:/flutter/.pub-cache/hosted/
pub.dartlang.org/dio-2.2.2/lib/src/dio_http_headers.dart:70:8: Error: The
method 'DioHttpHeaders.set' has fewer named arguments than those of
overridden method 'HttpHeaders.set'.
  void set(String name, Object value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:703:8:
Context: This is the overridden method ('set').
  void set(String name, Object value,
       ^

Compiler message:
/C:/flutter/.pub-cache/hosted/
pub.dartlang.org/dio-2.2.2/lib/src/dio_http_headers.dart:55:8: Error: The
method 'DioHttpHeaders.add' has fewer named arguments than those of
overridden method 'HttpHeaders.add'.
  void add(String name, value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:694:8:
Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^
/C:/flutter/.pub-cache/hosted/
pub.dartlang.org/dio-2.2.2/lib/src/dio_http_headers.dart:70:8: Error: The
method 'DioHttpHeaders.set' has fewer named arguments than those of
overridden method 'HttpHeaders.set'.
  void set(String name, Object value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:703:8:
Context: This is the overridden method ('set').
  void set(String name, Object value,
       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation:
null
build failed.

FAILURE: Build failed with an exception.
* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero
exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 1m 42s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by JoshuaR503** [comment]
@360views, I have followed the following steps: 

- `git clone https://github.com/JoshuaR503/Stock-Market-App.git`
- `code Stock-Market-App`
- Replace API keys
- Run virtual simulator in debug mode

Everything worked just fine. Please provide your Flutter version by running `flutter doctor -v`.
It would be great if you could provide a detailed guide step by step of how you're getting this error. 

Reading the stack trace, I thought that it could be a Dio Error. If so, try this: https://github.com/flutterchina/dio/issues/780.

**Comment by 360views** [comment]
Hi - please check if your App is working - "There was an unknown error" 
News is working well

**Comment by 360views** [comment]
this is the DEBUG:

W/IInputConnectionWrapper( 6001): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 6001): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 6001): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 6001): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6001): endBatchEdit on inactive InputConnection
I/flutter ( 6001): NoSuchMethodError: The method '[]' was called on null.
I/flutter ( 6001): Receiver: null
I/flutter ( 6001): Tried calling: []("symbol")
I/flutter ( 6001): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
I/flutter ( 6001): #1      new StockQuote.fromJson 
package:sma/…/profile/stock_quote.dart:46
I/flutter ( 6001): #2      ProfileClient.fetchStockData 
package:sma/…/profile/client.dart:29
I/flutter ( 6001): <asynchronous suspension>
I/flutter ( 6001): #3      ProfileBloc._mapProfileState 
package:sma/…/profile/profile_bloc.dart:34
I/flutter ( 6001): <asynchronous suspension>
I/flutter ( 6001): #4      ProfileBloc.mapEventToState 
package:sma/…/profile/profile_bloc.dart:27
I/flutter ( 6001): <asynchronous suspension>

**Comment by JoshuaR503** [comment]
@360views, the reason why my app isn't working is because the Portfolio and the Market sections rely on the same API. Sadly, they added a limit and after 250 request, those two sections of the app will stop working.

**Comment by dudd9d92** [comment]
So you're saying to you're getting an error as well? We don't think it's your API limit request. Try CREATING a new API account and replace the keys. Your app doesn't work, only the News work.

**Comment by JoshuaR503** [comment]
If my app didn't work, the news sections wouldn't work either.

**Comment by sarveshag25** [comment]
hi , i am getting  this error 
MissingPluginException(No implementation found for method check on channel plugins.flutter.io/connectivity)
